# task config
task: singlecombat_shoot

# simulation config
sim_freq: 60
agent_interaction_steps: 12 # step 0.2s

# termination config
max_steps: 1000             # episode length: 200s
altitude_limit: 2500
acceleration_limit_x: 10.0
acceleration_limit_y: 10.0
acceleration_limit_z: 10.0

# (lontitude, latitude, altitude)
battle_field_center: [124.00, 37.00, 0.0]

# reward config
MissilePostureReward_scale: 30

PostureReward_scale: 15.0
PostureReward_potential: true
PostureReward_orientation_version: v2
PostureReward_range_version: v3

AltitudeReward_safe_altitude: 4.0
AltitudeReward_danger_altitude: 3.5
AltitudeReward_Kv: 0.2

EventDrivenReward_scale: 1
EventDrivenReward_potential: true